Create database Carsales; 

use Carsales;

SHOW TABLES;

describe Car_Sales;

select * from car_sales;


select count(*) from car_sales;

SELECT `Customer Name` 
FROM Car_Sales 
WHERE company = 'Ford' 
ORDER BY `Customer Name`;

				-- check how many gendercar_sales --

select distinct(gender) from car_sales;

				-- Sales Performance Analysis---

# 1.What is the total revenue generated by each dealer?
SELECT Dealer_Name, SUM(`Price ($)`) AS total_revenue  
FROM car_sales GROUP BY Dealer_Name  ORDER BY total_revenue DESC  LIMIT 1000;

#2.	Which dealer has the highest number of sales?
select Dealer_Name, count(ï»¿Car_id) as number_of_order
from Car_sales group by Dealer_Name order by number_of_order desc limit 6;

#3.What is the average price of cars sold by each dealer?
SELECT Dealer_Name, CAST(AVG(`Price ($)`) AS UNSIGNED) AS average_price  
FROM Car_sales  GROUP BY Dealer_Name  ORDER BY average_price DESC;

				-- Customer Demographics and Behavior --

#1.What is the gender distribution of customers?
select gender , count(gender) as number_gender
from car_sales group by gender order by number_gender desc;

#2.What is the average annual income of customers?
SELECT `Customer Name`, CAST(AVG(`Annual Income`) AS UNSIGNED) AS avg_annual_income  
FROM car_sales  GROUP BY `Customer Name`  ORDER BY avg_annual_income DESC;

#3.What is the distribution of customers based on the dealer regions?
select Dealer_Region as region,count(Dealer_Region) as customers_regions
from Car_Sales group by region order by customers_regions desc;

				-- Model and Company Insights --

#1.What are the top 5 most popular car models?
select model, count(ï»¿Car_id) as number_of_sales
from Car_Sales group by model order by number_of_sales desc limit 5;

#2.Which company has the highest sales volume?
select company, count(ï»¿Car_id) as sales_volume
from car_sales group by company order by sales_volume desc limit 5;

#3.What is the average price of cars from each company?
select company , cast(avg(`Price ($)`) as decimal(5,2) )as average_price
from car_sales group by company order by average_price desc;

SELECT company, CAST(AVG(`Price ($)`) AS UNSIGNED) AS average_price  
FROM Car_Sales  GROUP BY company  ORDER BY average_price DESC;

				-- Regional Analysis --

# 1.Which dealer region has the highest sales revenue?
select dealer_region, count(ï»¿Car_id) as sales_volume
from car_sales group by dealer_region order by sales_volume desc limit 1 offset 0;

# 2.Which dealer region has the 2nd highest sales revenue?
select dealer_region, count(ï»¿Car_id) as sales_volume
from car_sales group by dealer_region order by sales_volume desc limit 1 offset 1;

#3.What is the sales performance comparison between different dealer regions?
select dealer_region,
sum(`Price ($)`) as total_sales,
round(avg(`Price ($)`)) as avg_sales,
count(ï»¿Car_id) as no_of_sales
from car_sales group by dealer_region order by total_sales desc;

#4.How does the average car price vary across different regions?
select dealer_region as region,round(avg(`Price ($)`)) as avg_price
from car_sales group by region order by avg_price desc;

				-- Engine and Transmission Preferences --

select distinct(engine) from car_sales;

#1.What is the distribution of engine types among sold cars?
select engine as Engine_Type,count(ï»¿Car_id) as number_of_car_sold
from car_sales group by Engine_Type order by number_of_car_sold desc;

#2.What percentage of cars sold have automatic vs. manual transmission?
SELECT TRANSMISSION , COUNTS , 
(COUNTS *100.0 / (SELECT COUNT(*) FROM CAR_SALES) ) AS PERCENTAGE
FROM(
SELECT TRANSMISSION , COUNT(TRANSMISSION) COUNTS 
FROM CAR_SALES
GROUP BY TRANSMISSION  ORDER BY COUNTS DESC
) AS TRAN;

				-- Color and Body Style Trends --

#1.What are the top 3 most popular car colors?
SELECT COLOR , COUNT(ï»¿Car_id) AS POPULAR_SALES 
FROM CAR_SALES GROUP BY COLOR ORDER BY POPULAR_SALES DESC LIMIT 3;

#2.What is the distribution of body styles among sold cars?
SELECT 'Body Style' , COUNT(ï»¿Car_id) AS SOLD_CARS 
FROM CAR_SALES GROUP BY 'Body Style' ORDER BY SOLD_cARS DESC;

				-- Dealer Performance --

#1.What is the total number of sales made by each dealer?
SELECT DEALER_NAME, COUNT(ï»¿Car_id) NO_OF_SALES
FROM CAR_SALES GROUP BY DEALER_NAME ORDER BY NO_OF_SALES DESC;

#2.Which dealer has the highest average sales price?
SELECT DEALER_NAME, ROUND(AVG(`Price ($)`)) AS AVG_PRICE  
FROM CAR_SALES  
GROUP BY DEALER_NAME  
ORDER BY AVG_PRICE DESC  
LIMIT 1;














